baseURL = "https://tsuha0.github.io/"
languageCode = "zh-CN"
title = "Tsuhao的博客"
theme = "maupassant"
googleAnalytics = "G-TW3Z27YPGS"

## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
## 是否禁止URL Path转小写
disablePathToLower = true

hasCJKLanguage = true
summaryLength = 140


[author]
  name = "Tsuhao"

[params]
  author = "Tsuhao"
  subtitle = "USTC在读，正在学习Golang/C++"
  keywords = "golang C++"
  description = "s"
  busuanzi = true #启用不算子网页统计
  googleAd = ""  #ca-pub-xxxxxxxxxxxxxx
  localSearch = true # 启用本地搜索

  # 这里我存放在了主题的static文件夹里，根目录的似乎也可以
  customCSS = ['douban.css', 'other.css','add-copy-btn.css']
  # if ['custom.css'], load '/static/css/custom.css' file
  customJS = ['douban.js', 'add-copy-btn.js']
  # if ['custom.js'], load '/static/js/custom.js' file

  # 全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能
  toc = false  # 是否开启目录

## 友情链接，可以多个

[[params.links]]
  title = "飞雪无情的博客"
  name = "飞雪无情的博客"
  url = "https://www.flysnow.org/"


## 侧边栏广告位
##[[params.ads]]
##  title = 
##  url = 
##  img = 


## 配置 utteranc评论,教程参考 https://utteranc.es/
[params.utteranc]
  enable = true
  repo = "TSUHA0/BlogCommit"
  issueTerm = "pathname"
  theme = "github-light"

## 开启版权声明，协议名字和链接都可以换
[params.cc]
    name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
    link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

## 配置代码高亮
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 4
    

## 配置网站菜单

[menu]

  [[menu.main]]
    identifier = "project"
    name = "项目"
    url = "/project/"
    weight = 2

  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 3

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 4
